export const GROCERY_CATEGORIES: { category: string; items: string[] }[] = [
  {
    category: 'Vegetables',
    items: [
      'Onion',
      'Tomato',
      'Potato',
      'Bendakaya (Okra)',
      'Dondakaya (Tindora)',
      'Beans',
      'Carrot',
      'Capsicum',
      'Cabbage',
      'Cauliflower',
      'Brinjal (Eggplant)',
      'Cucumber',
      'Spinach',
      'Coriander',
      'Curry Leaves',
      'Mint',
      'Green Chili',
      'Ginger',
      'Garlic',
      'Lemon',
    ],
  },
  {
    category: 'Grains & Pulses',
    items: [
      'Rice',
      'Wheat Flour (Atta)',
      'Dal (Lentils)',
      'Rava/Sooji',
      'Urad Dal',
      'Toor Dal',
      'Chana Dal',
      'Moong Dal',
      'Kala Chana',
      'Kabuli Chana',
      'Groundnuts',
      'Kidney Beans (Rajma)',
      'Sabudana',
      'Semiya',
      'Oats',
      'Quinoa',
      'Maggi Noodles',
      'Macaroni',
      'Soya Chunks (Meal Maker)',
      'Fryums',
    ],
  },
  {
    category: 'Dairy',
    items: ['Milk', 'Curd', 'Butter', 'Paneer', 'Cheese', 'Ghee', 'Lassi'],
  },
  {
    category: 'Oil & Spices',
    items: [
      'Cooking Oil',
      'Salt',
      'Sugar',
      'Turmeric',
      'Chili Powder',
      'Mustard Seeds',
      'Cumin Seeds',
      'Coconut Oil',
      'Gingelly Oil',
      'Karam Podi',
      'MTR Sambar Powder',
      'Puliyogare Mix',
      'Chicken Masala',
      'Mutton Masala',
      'Fish Masala',
      'Hing (Asafoetida)',
      'Coriander Powder',
      'Coriander Seeds',
      'Dry Chillies',
      'Sesame Seeds',
      'Biryani Leaves',
      'Baking Soda',
      'Rose Water',
      'Jaggery',
      'Maida (All-Purpose Flour)',
    ],
  },
  {
    category: 'Fruits',
    items: [
      'Banana',
      'Apple',
      'Mango',
      'Orange',
      'Watermelon',
      'Cantaloupe',
      'Strawberry',
      'Blueberry',
      'Plums',
      'Grapes',
      'Cranberries',
      'Cherries',
    ],
  },
  {
    category: 'Nuts & Dry Fruits',
    items: ['Walnuts', 'Almonds', 'Pistachio', 'Desiccated Coconut Powder', 'Dry Coconut'],
  },
  {
    category: 'Other',
    items: [
      'Eggs',
      'Bread',
      'Tea',
      'Coffee',
      'Corn Flakes',
      'Honey',
      'Pasta Sauce',
      'Chicken',
      'Ketchup',
      'Alfredo Sauce',
      'Frozen Green Peas',
      'Frozen Beans',
      'Fried Onions',
    ],
  },
  {
    category: 'Household & Personal Care',
    items: [
      'Floor Cleaner',
      'Dishwasher Liquid',
      'Dishwasher Cubes',
      'Scrubber',
      'Soap',
      'Shampoo',
      'Comb',
      'Ziploc Bags',
      'Trash Bags',
    ],
  },
]
