export const GROCERY_CATEGORIES: { category: string; items: string[] }[] = [
  {
    category: 'Vegetables',
    items: [
      'Onion',
      'Tomato',
      'Potato',
      'Bendakaya (Okra)',
      'Dondakaya (Tindora)',
      'Kakarakaya (Bitter Gourd)',
      'Beans',
      'Carrot',
      'Capsicum',
      'Cabbage',
      'Cauliflower',
      'Brinjal (Eggplant)',
      'Cucumber',
      'Spinach',
      'Coriander',
      'Curry Leaves',
      'Mint',
      'Green Chili',
      'Ginger',
      'Garlic',
      'Lemon',
      'Beetroot',
      'Sorakaya (Bottle Gourd)',
      'Gongura',
      'Ginger Garlic Paste',
    ],
  },
  {
    category: 'Grains & Pulses',
    items: [
      'Rice',
      'Wheat Flour (Atta)',
      'Readymade Chapatis',
      'Dal (Lentils)',
      'Rava/Sooji',
      'Urad Dal',
      'Toor Dal',
      'Chana Dal',
      'Moong Dal',
      'Kala Chana',
      'Kabuli Chana',
      'Groundnuts',
      'Kidney Beans (Rajma)',
      'Sabudana',
      'Semiya',
      'Oats',
      'Quinoa',
      'Maggi Noodles',
      'Macaroni',
      'Soya Chunks (Meal Maker)',
      'Fryums',
      'Millets',
      'Jowar (Sorghum)',
      'Yellow Moong Dal',
      'Besan (Gram Flour)',
    ],
  },
  {
    category: 'Dairy & Meat',
    items: ['Milk', 'Curd', 'Butter', 'Paneer', 'Cheese', 'Ghee', 'Lassi', 'Eggs', 'Chicken', 'Mutton', 'Fish'],
  },
  {
    category: 'Oil & Spices',
    items: [
      'Sunflower Oil',
      'Salt',
      'Sugar',
      'Turmeric',
      'Chili Powder',
      'Mustard Seeds',
      'Cumin Seeds',
      'Coconut Oil',
      'Gingelly Oil',
      'Groundnut Cold-Pressed Oil',
      'Avocado Oil',
      'Karam Podi',
      'MTR Sambar Powder',
      'Puliyogare Mix',
      'Chicken Masala',
      'Mutton Masala',
      'Fish Masala',
      'Hing (Asafoetida)',
      'Coriander Powder',
      'Coriander Seeds',
      'Dry Chillies',
      'Sesame Seeds',
      'Biryani Leaves',
      'Baking Soda',
      'Rose Water',
      'Jaggery',
      'Maida (All-Purpose Flour)',
      'Tamarind',
    ],
  },
  {
    category: 'Fruits',
    items: [
      'Banana',
      'Apple',
      'Mango',
      'Orange',
      'Watermelon',
      'Cantaloupe',
      'Strawberry',
      'Blueberry',
      'Plums',
      'Grapes',
      'Cranberries',
      'Cherries',
      'Avocado',
    ],
  },
  {
    category: 'Nuts & Dry Fruits',
    items: ['Walnuts', 'Almonds', 'Pistachio', 'Desiccated Coconut Powder', 'Dry Coconut'],
  },
  {
    category: 'Other',
    items: [
      'Bread',
      'Tea',
      'Coffee',
      'Corn Flakes',
      'Honey',
      'Pasta Sauce',
      'Ketchup',
      'Alfredo Sauce',
      'Frozen Green Peas',
      'Frozen Beans',
      'Fried Onions',
      'Cookies',
    ],
  },
  {
    category: 'Alcohol',
    items: ['Wine', 'Beer', 'Whiskey'],
  },
  {
    category: 'Household & Personal Care',
    items: [
      'Floor Cleaner',
      'Dishwasher Liquid',
      'Dishwasher Cubes',
      'Scrubber',
      'Soap',
      'Shampoo',
      'Comb',
      'Ziploc Bags',
      'Trash Bags',
      'Bath Tissues',
      'Paper Towels',
      'Nail Cutter',
      'Pads',
      'Hand Wash',
      'Car Shampoo',
      'Softener Salt',
      'HVAC Filters',
      'Clorox Liquid',
      'Magic Eraser',
      'Toothbrush',
      'Toothpaste',
    ],
  },
  {
    category: 'Health & First Aid',
    items: ['Tylenol', 'Ibuprofen', 'Zandu Balm', 'Neosporin', 'Eye Drops', 'Ear Drops', 'Bandage Strips'],
  },
]
